version: '3.8'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: si_akutansi
    volumes:
      - ./mysql_data:/var/lib/mysql
